[versions] 
# Engine dari KernelSU (Bleeding Edge)
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.0-1.0.27"
compose-bom = "2025.01.00"
kotlinxSerialization = "1.6.3"

# UI & Library
material3 = "1.5.0-alpha11"
activity-compose = "1.12.2"
lifecycle = "2.10.0"
navigation = "2.9.6"

# Security & Glassmorphism
stringfog = "5.1.0"
stringfogXor = "5.0.0"
haze = "1.3.0"

coil-compose = "2.7.0"
appiconloader-coil = "1.5.0"
ucrop = "2.2.11"
appcompat = "1.7.1"
androidx-transition = "1.7.0-rc01"
lifecycleViewModel = "2.7.0"

# Tools
libsu = "6.0.0"

[libraries]
androidx-transition = { group = "androidx.transition", name = "transition", version.ref = "androidx-transition" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-core = { group = "androidx.compose.animation", name = "animation-core" }
# Core Android & Lifecycle
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

io-coil-kt-coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
me-zhanghai-android-appiconloader-coil = { group = "me.zhanghai.android.appiconloader", name = "appiconloader-coil", version.ref = "appiconloader-coil" }

# StringFog (Security)
stringfog-xor = { group = "com.github.megatronking.stringfog", name = "xor", version.ref = "stringfogXor" }

# Haze (Glassmorphism)
haze = { module = "dev.chrisbanes.haze:haze-android", version.ref = "haze" }

# Libsu 
com-github-topjohnwu-libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
com-github-topjohnwu-libsu-service = { group = "com.github.topjohnwu.libsu", name = "service", version.ref = "libsu" }
com-github-topjohnwu-libsu-io = { group = "com.github.topjohnwu.libsu", name = "io", version.ref = "libsu" }

material-kolor = { group = "com.materialkolor", name = "material-kolor", version = "4.0.5" }

yalantis-ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }


[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
stringfog = { id = "stringfog", version.ref = "stringfog" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.0" } 
