name: AZenith

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "cargo/**"
      - "tweakfls/**"
      - "mainfiles/**"
      - "preloadbin/**"
      - "webui/**"
      - "thermalcore/**"
      - "gamelist.txt"
      - "version"

# Allow only one concurrent build workflows
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable ZIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: NDK Setup
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r29

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Add ARCH Target
        run: |
          rustup target add \
          aarch64-linux-android \
          armv7-linux-androideabi \
          i686-linux-android \
          x86_64-linux-android 

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Build Rust Daemon
        run: |
          cd ./cargo
          cargo ndk --target aarch64-linux-android build --release
          cargo ndk --target armv7-linux-androideabi build --release

          echo "Stripping binaries..."
          $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip target/aarch64-linux-android/release/sys.azenithnonr-service
          $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip target/armv7-linux-androideabi/release/sys.azenithnonr-service
       
          echo "Compressing with UPX..."
          upx --best --lzma target/aarch64-linux-android/release/sys.azenithnonr-service
          upx --best --lzma target/armv7-linux-androideabi/release/sys.azenithnonr-service

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Building WebRoots
        working-directory: ./webui
        run: |
          bun install
          bun run build
          cp -r ./dist/* ../mainfiles/webroot

      - name: Compile Flashable Zip
        id: compileZip
        run: bash .github/scripts/compile_zip.sh

      - name: Upload To Telegram
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: AZenithEunoia
        run: |
          if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            export VERSION=$(git rev-list --count HEAD)
            bash .github/scripts/telebot.sh ${{ steps.compileZip.outputs.zipName }}
          else
            echo "Telegram bot token or chatid is undefined, please add it to repository secrets!"
            exit 1
          fi

      - name: Unzip AZenith Package
        run: |
          unzip ${{ steps.compileZip.outputs.zipName }} -d extracted

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.compileZip.outputs.zipName }}
          path: extracted/**
